#!/usr/bin/env ruby
arg = ARGV
def encrypt(sentence, key=0)
  coded = ""
  key_mod = key % 26
  sentence.each_char do |letter|

    if (65..90).include? letter.ord
      new = (letter.ord + key_mod)
      if new > 90
      new = new % 90 + 65
      end
      coded +=  new.chr
    elsif (97..122).include? letter.ord
      new = (letter.ord + key_mod)
      if new > 122
      new = new % 122 + 97
      end
      coded +=  new.chr
    else
      coded += letter
    end
  end
  puts coded
end

encrypt(arg[0],arg[1].to_i)
